name: Daily Script Execution

on:
  schedule:
    - cron: '15 17 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script
        run: |
          /path/to/your/virtualenv/bin/python /path/to/your/script.py
